version: "3.5"
services:
    nginx:
        image: nginx:latest
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - ./hosts/:/etc/nginx/conf.d
            - ./www/:/var/www:cached
            - ./logs:/var/log/nginx
        depends_on:
            - php
        links:
            - php
    php:
        build: ./images/php
        depends_on:
            - mysql
        links:
            - mysql
        volumes:
            - ./www:/var/www
    mysql:
        image: mariadb:10.3
        ports:
            - "3306:3306"
        volumes:
            - ./dumps/:/var/dumps
            - ./mysql/:/var/lib/mysql
        environment:
            MYSQL_HOST: 'mysql'
            MYSQL_BIND_ADDRESS: '0.0.0.0'
            MYSQL_USER: 'user'
            MYSQL_PASSWORD: '123456'
            MYSQL_ROOT_PASSWORD: 'root'
            MYSQL_DATABASE: web_app
            MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
            LANG: C.UTF_8
        command: ['mysqld', '--log-bin-trust-function-creators=1', '--sql-mode=', '--lower_case_table_names=1', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci', '--default-authentication-plugin=mysql_native_password']
